name: Main
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl -LO https://github.com/rust-lang/mdBook/releases/download/${{ vars.MDBOOK_VERSION }}/mdbook-${{ vars.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
      - run: tar -xzf mdbook-${{ vars.MDBOOK_VERSION }}-x86_64-unknown-linux-gnu.tar.gz
      - run: chmod +x mdbook
      - run: sudo mv mdbook /usr/local/bin/mdbook
      - run: mdbook build src/en -d ../../book/en
      - run: mdbook build src/fa -d ../../book/fa
      - run: cp src/static/index.html book/index.html
      - name: Upload Static Pages
        uses: actions/upload-artifact@v4
        with:
          name: static-pages
          path: book

  deploy-github-pages:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Static Pages
        uses: actions/download-artifact@v4
        with:
          name: static-pages
          path: book
      - name: Deploy To The Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: book
